##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-session-manager
    - autoconf-archive
    - clang
    - dbus-glib
    - gcc
    - git
    - gtk3
    - intltool
    - libsm
    - make
    - mate-common
    - mate-desktop
    - python
    - systemd
    - which
    - xtrans

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-session-manager
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - intltool
    - libdbus-glib-1-dev
    - libgl1-mesa-dev
    - libgles2-mesa-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libice-dev
    - libsm-dev
    - libstartup-notification0-dev
    - libsystemd-dev
    - libx11-dev
    - libxau-dev
    - libxext-dev
    - libxrender-dev
    - libxt-dev
    - libxtst-dev
    - make
    - mate-common
    - xmlto
    - xsltproc

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-session-manager.git
    - autoconf-archive
    - clang
    - clang-analyzer
    - dbus-glib-devel
    - desktop-file-utils
    - gcc
    - git
    - gtk3-devel
    - libSM-devel
    - libXtst-devel
    - make
    - mate-common
    - mesa-libGLES-devel
    - pango-devel
    - redhat-rpm-config
    - systemd-devel
    - xmlto
    - xorg-x11-xtrans-devel

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - gcc
    - git
    - intltool
    - libdbus-glib-1-dev
    - libgl1-mesa-dev
    - libgles2-mesa-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libice-dev
    - libsm-dev
    - libstartup-notification0-dev
    - libsystemd-dev
    - libx11-dev
    - libxau-dev
    - libxext-dev
    - libxrender-dev
    - libxt-dev
    - libxtst-dev
    - make
    - mate-common
    - xmlto
    - xsltproc

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-session-manager-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
